# Generated by Django 4.2.8 on 2023-12-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tg', models.CharField(max_length=255, unique=True, verbose_name='Тг юзера')),
                ('user_hwid', models.CharField(max_length=255, unique=True, verbose_name='HWID пользователя')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания лицензии')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
            },
        ),
    ]
